services:
  - type: web
    name: backend-panaderia
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: panaderia_jz87
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: panaderia_jz87
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: panaderia_jz87
          property: password
